general:
  verbose: true
  buildTool: 'mta'
steps:
  artifactSetVersion:
    commitVersion: false
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    mtaDeployParameters: '--version-rule ALL'
    cloudFoundry:
      org: 'OpenSAP-DEV'
      space: 'dev'
      credentialsId: 'cfDeploy'
  tmsUpload:
    mtaPath: 'DemoApp.mtar'
    nodeName: 'OpenSAP_DEV'
    credentialsId: 'tms'
    
